name: biblebookapp
description: A new Flutter project.

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.69+69

environment:
  sdk: ">=3.5.4 <4.0.0"

dependencies:
  android_id: ^0.4.0
  path: ^1.9.1
  app_tracking_transparency: ^2.0.4
  archive: ^4.0.2
  audio_video_progress_bar: ^2.0.3
  audioplayers: ^6.1.2
  audio_service: ^0.18.7
  flutter_pdfview: ^1.4.1+1
  auto_size_text: ^3.0.0
  cached_network_image: ^3.3.1
  carousel_slider_plus: ^7.0.0
  chips_choice: ^3.0.1
  cloud_firestore: ^5.6.3
  connectivity_plus: ^7.0.0
  country_picker: ^2.0.26
  crypto: ^3.0.5
  cupertino_icons: ^1.0.2
  day_night_time_picker: ^1.3.1
  device_info_plus: ^11.3.0
  dio: ^5.8.0+1
  dots_indicator: ^4.0.0
  dropdown_button2: ^2.3.9
  encrypt: ^5.0.3
  file_picker: ^8.1.2
  firebase_analytics: ^11.4.2
  firebase_app_installations: ^0.3.1+3
  firebase_auth: ^5.3.1
  firebase_core: ^3.6.0
  firebase_crashlytics: ^4.3.2
  firebase_in_app_messaging: ^0.8.1+2
  firebase_messaging: ^15.2.2
  firebase_storage: ^12.4.2
  flutter:
    sdk: flutter
  flutter_advanced_switch: ^3.0.1
  flutter_dialogs: ^3.0.0
  flutter_dotenv: ^5.1.0
  flutter_easyloading: ^3.0.5
  flutter_facebook_auth: ^7.1.1
  flutter_hooks: ^0.20.4
  flutter_inappwebview: ^6.1.5
  flutter_local_notifications: ^18.0.1
  flutter_otp_text_field: ^1.5.1+1
  flutter_picker: ^2.1.0
  flutter_rating_bar: ^4.0.1
  flutter_staggered_grid_view: ^0.7.0
  flutter_svg: ^2.0.17
  flutter_switch: ^0.3.2
  flutter_time_picker_spinner: ^2.0.0
  flutter_tts: ^4.0.2
  flutter_widget_from_html_core: ^0.15.2
  form_builder_validators: ^11.1.1
  get: ^4.7.1
  get_storage: ^2.1.1
  google_generative_ai: ^0.4.3
  google_mobile_ads: ^6.0.0
  google_sign_in: ^6.2.1
  hooks_riverpod: ^2.4.9
  html: ^0.15.4
  html_unescape: ^2.0.0
  http: ^1.3.0
  image_gallery_saver_plus: ^4.0.0-0.alpha
  image_picker: ^1.1.2
  in_app_purchase: ^3.2.0
  in_app_purchase_android: ^0.4.0
  in_app_purchase_platform_interface: ^1.4.0
  in_app_purchase_storekit: ^0.3.13+1
  in_app_review: ^2.0.11
  # intl: ^0.19.0
  intl: ^0.20.2
  lottie: ^3.3.1
  numberpicker: ^2.0.1
  open_file_manager: ^1.0.3
  package_info_plus: ^8.2.1
  path_provider: ^2.1.5
  percent_indicator: ^4.2.4
  permission_handler: ^11.3.1
  photo_view: ^0.15.0
  popover: ^0.3.1
  pretty_http_logger: ^1.0.4
  provider: ^6.1.2
  rxdart: ^0.28.0
  screenshot: ^3.0.0
  scroll_to_index: ^3.0.1
  share_plus: ^10.1.4
  shared_preferences: ^2.5.2
  shimmer: ^3.0.0
  statsig: ^1.0.0
  sign_in_with_apple: ^6.1.3
  simple_gesture_detector: ^0.2.1
  smooth_page_indicator: ^1.2.0+3
  speech_to_text: ^7.0.0
  sqflite: ^2.2.7
  sqflite_sqlcipher: ^3.1.0+1
  timezone: ^0.9.4
  upgrader: ^11.4.0
  url_launcher: ^6.3.1
  internet_connection_checker_plus: ^2.9.0
  syncfusion_flutter_pdfviewer: ^31.1.21
#  flutter_localized_locales: ^2.0.4
dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
# The following section is specific to Flutter packages.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  assets:
    - assets/
    - assets/Bookmark icons/
    - assets/Library icons/
    - assets/home icons/
    - assets/lightMode/
    - assets/lightMode/icons/
    - assets/lightMode/images/
    - assets/nightMode/
    - assets/nightMode/icons/
    - assets/nightMode/images/
    - assets/jsonFile/
    - assets/homeicon/
    - assets/offer/
    - assets/zipped/
    - assets/zipped/Geneva Bible/
    - assets/icons/
    - assets/onboarding/
    - .env

  fonts:
    - family: Arial
      fonts:
        - asset: assets/fonts/ARIAL.TTF
          weight: 500
    - family: Georgia
      fonts:
        - asset: assets/fonts/GEORGIA.ttf
          weight: 500
    - family: Tahoma
      fonts:
        - asset: assets/fonts/TAHOMA.TTF
          weight: 500
    - family: Trebuchet MS
      fonts:
        - asset: assets/fonts/TERBUCHET.ttf
          weight: 500
    - family: Times New Roman
      fonts:
        - asset: assets/fonts/TIMESNEWROMAN.ttf
          weight: 500
    - family: Verdana
      fonts:
        - asset: assets/fonts/VERDANA.ttf
          weight: 500
    - family: Garamond Regular
      fonts:
        - asset: assets/fonts/Garamond_Regular.ttf
          weight: 500
    - family: Courier New
      fonts:
        - asset: assets/fonts/Courier_New.ttf
          weight: 500
    - family: Brush Script MT
      fonts:
        - asset: assets/fonts/BRUSHSCI.ttf

    - family: Courier
      fonts:
        - asset: assets/fonts/Courier.ttf

    - family: Alnile
      fonts:
        - asset: assets/fonts/Alnile.ttf

    - family: Avenir LT Std 65 Medium
      fonts:
        - asset: assets/fonts/Avenir.otf

#    - family: Cochin
#      fonts:
#        - asset: assets/fonts/Cochin.ttf
